stages: # List of stages for jobs, and their order of execution
  - deploy

deploy-3min-release-fe:
  only:
    refs:
      - main
      - master
  stage: deploy

  when: manual

  tags:
    - nodejs-build
  environment: production
  script:
    - chmod +x deploy.sh
    - ./deploy.sh 3min

deploy-3min-pre-release-fe:
  only:
    refs:
      - /^release/v\d+\.\d+\.\d+.*$/
  stage: deploy

  when: manual

  tags:
    - nodejs-build
  environment: production
  script:
    - chmod +x deploy.sh
    - ./deploy.sh 3min_p


deploy-devmentor-fe:
  only:
    refs:
      - develop
  stage: deploy

  when: manual

  tags:
    - nodejs-build
  environment: production
  script:
    - chmod +x deploy.sh
    - ./deploy.sh devmentor